# Generated by Django 5.2 on 2025-05-10 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("dateC", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("brut", "Fichier brut"),
                            ("nettoye", "Fichier nettoye"),
                        ],
                        default="brut",
                        max_length=100,
                    ),
                ),
                (
                    "format_fichier",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON")],
                        default="csv",
                        max_length=50,
                    ),
                ),
                ("fichier", models.FileField(upload_to="datasets/")),
            ],
        ),
        migrations.CreateModel(
            name="ModeleML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "algorithme",
                    models.CharField(
                        choices=[
                            ("isolation_forest", "Isolation Forest"),
                            ("svm", "SVM"),
                            ("kmeans", "K-Means"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "type_fraude",
                    models.CharField(
                        choices=[
                            ("cartes", "Cartes virtuelles"),
                            ("transactions", "Transactions"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fichier_modele",
                    models.FileField(blank=True, null=True, upload_to="modeles_ml/"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegleMetier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "condition",
                    models.TextField(help_text="Exemple : montant > 1000000"),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campagne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("suspendue", "Suspendue"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("quotidien", "Chaque jour"),
                            ("hebdomadaire", "Chaque semaine"),
                            ("bihebdomadaire", "Deux fois par semaine"),
                            ("mensuel", "Chaque mois"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "repetition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1h", "Toutes les 1 heure"),
                            ("6h", "Toutes les 6 heures"),
                            ("12h", "Toutes les 12 heures"),
                            ("24h", "Toutes les 24 heures"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "date_debut_c",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_fin_c", models.DateTimeField(blank=True, null=True)),
                (
                    "datasets",
                    models.ManyToManyField(
                        related_name="campagnes", to="SoleasDectection.dataset"
                    ),
                ),
                (
                    "modele_ml",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagnes",
                        to="SoleasDectection.modeleml",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GestionnaireRisque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("rapport", models.TextField(blank=True, null=True)),
                (
                    "campagne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports",
                        to="SoleasDectection.campagne",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("nom", models.CharField(max_length=200)),
                ("matricule", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("bloque", "Bloqué"),
                            ("legitime", "Faux positif / Légitime"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "campagne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspects",
                        to="SoleasDectection.gestionnairerisque",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Administrateur"), ("analyste", "Analyste")],
                        default="analyste",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campagne",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campagnes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
