# Generated by Django 5.2 on 2025-05-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0002_alter_dataset_fichier"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeleTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_test", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("succes", "Succes"), ("échec", "Echec")],
                        default="succès",
                        max_length=20,
                    ),
                ),
                ("resultat", models.JSONField(blank=True, null=True)),
                ("graph_data", models.JSONField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SoleasDectection.dataset",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SoleasDectection.modeleml",
                    ),
                ),
            ],
        ),
    ]
