# Generated by Django 5.2 on 2025-05-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0003_modeletest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeletest",
            name="statut",
            field=models.CharField(
                choices=[("succes", "Succes"), ("échec", "Echec")],
                default="succes",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SuspectTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("matricule", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "modele_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspects",
                        to="SoleasDectection.modeletest",
                    ),
                ),
            ],
        ),
    ]
