# Generated by Django 5.2 on 2025-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0004_alter_modeletest_statut_suspecttest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suspecttest",
            old_name="nom",
            new_name="username",
        ),
        migrations.AddField(
            model_name="modeletest",
            name="fichier_fraude",
            field=models.FileField(
                blank=True, null=True, upload_to="resultats_fraude/"
            ),
        ),
        migrations.AddField(
            model_name="suspecttest",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
