# Generated by Django 5.2 on 2025-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0005_rename_nom_suspecttest_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeletest",
            name="resultat",
        ),
        migrations.AddField(
            model_name="modeletest",
            name="nb_fraudes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modeletest",
            name="nb_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modeletest",
            name="nom_fichier_resultat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
