# Generated by Django 5.2 on 2025-05-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SoleasDectection",
            "0006_remove_modeletest_resultat_modeletest_nb_fraudes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeletest",
            name="statut",
            field=models.CharField(
                choices=[("succes", "Succes"), ("echec", "Echec")],
                default="succes",
                max_length=20,
            ),
        ),
    ]
