# Generated by Django 5.2 on 2025-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0007_alter_modeletest_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeletest",
            name="graph_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
