# Generated by Django 5.2 on 2025-05-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0008_alter_modeletest_graph_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeletest",
            name="rapport_test_pdf",
            field=models.FileField(blank=True, null=True, upload_to="rapports_test/"),
        ),
        migrations.AddField(
            model_name="suspecttest",
            name="decision",
            field=models.CharField(
                choices=[
                    ("suspect", "Suspect"),
                    ("legitime", "Legitime"),
                    ("en_attente", "En attente"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="suspecttest",
            name="description",
            field=models.TextField(default="Utilisateur considere comme suspect"),
        ),
    ]
