# Generated by Django 5.2 on 2025-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0010_dataset_fichier_brut"),
    ]

    operations = [
        migrations.AddField(
            model_name="suspecttest",
            name="is_fraud",
            field=models.BooleanField(default=False),
        ),
    ]
