# Generated by Django 5.2 on 2025-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0011_suspecttest_is_fraud"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suspecttest",
            name="is_fraud",
            field=models.IntegerField(),
        ),
    ]
