# Generated by Django 5.2 on 2025-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0012_alter_suspecttest_is_fraud"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeletest",
            name="fichier_suspects_temp",
            field=models.FileField(blank=True, null=True, upload_to="suspects_temp/"),
        ),
    ]
