# Generated by Django 5.2 on 2025-05-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0014_fichiersuspectstest"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichiersuspectstest",
            name="nom_fichier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
