# Generated by Django 5.2 on 2025-05-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0016_remove_fichiersuspectstest_fichier_csv"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeletest",
            name="fichier_suspects_temp",
        ),
        migrations.AddField(
            model_name="fichiersuspectstest",
            name="fichier_suspects_temp",
            field=models.FileField(blank=True, null=True, upload_to="suspects_temp/"),
        ),
    ]
