# Generated by Django 5.2 on 2025-05-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SoleasDectection",
            "0018_remove_fichiersuspectstest_fichier_suspects_temp_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeletest",
            name="rapport_test_pdf",
        ),
        migrations.AddField(
            model_name="fichiersuspectstest",
            name="rapport_test_pdf",
            field=models.FileField(blank=True, null=True, upload_to="rapports_test/"),
        ),
    ]
