# Generated by Django 5.2 on 2025-05-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0019_remove_modeletest_rapport_test_pdf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichiersuspectstest",
            name="rapport_test_pdf",
        ),
        migrations.AddField(
            model_name="modeletest",
            name="rapport_test_pdf",
            field=models.FileField(blank=True, null=True, upload_to="rapports_test/"),
        ),
    ]
