# Generated by Django 5.2 on 2025-06-01 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SoleasDectection",
            "0020_remove_fichiersuspectstest_rapport_test_pdf_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModeleTest",
            new_name="CampagneTest",
        ),
        migrations.RemoveField(
            model_name="fichiersuspectstest",
            name="modele_test",
        ),
        migrations.RemoveField(
            model_name="suspecttest",
            name="modele_test",
        ),
        migrations.AddField(
            model_name="fichiersuspectstest",
            name="campagne_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fichiers_suspects",
                to="SoleasDectection.gestionnairerisque",
            ),
        ),
        migrations.AddField(
            model_name="gestionnairerisque",
            name="campagne_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rapports",
                to="SoleasDectection.campagnetest",
            ),
        ),
        migrations.AddField(
            model_name="suspecttest",
            name="campagne_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suspects",
                to="SoleasDectection.gestionnairerisque",
            ),
        ),
        migrations.AlterField(
            model_name="gestionnairerisque",
            name="campagne",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="SoleasDectection.campagne",
            ),
        ),
        migrations.DeleteModel(
            name="Suspect",
        ),
    ]
