# Generated by Django 5.2 on 2025-06-03 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoleasDectection", "0021_rename_modeletest_campagnetest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichiersuspectstest",
            name="campagne_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fichiers_suspects",
                to="SoleasDectection.campagnetest",
            ),
        ),
        migrations.AlterField(
            model_name="gestionnairerisque",
            name="campagne_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gestionnaire",
                to="SoleasDectection.campagnetest",
            ),
        ),
        migrations.AlterField(
            model_name="suspecttest",
            name="campagne_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suspects",
                to="SoleasDectection.campagnetest",
            ),
        ),
    ]
