# Generated by Django 5.2 on 2025-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoleasDectection', '0022_alter_fichiersuspectstest_campagne_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
